# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI + Coveralls

on: ["push", "pull_request"]

jobs:
  build:
    name: Node.js CI + Coveralls

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3

      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        github-token: ${{ secrets.me_token }}
        
        
    - name: npm install
      run: npm install
      
    - run: npm ci
    - run: npm run build --if-present
    - run: c8 --reporter=lcovonly npm test
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.ME_TOKEN }}
